spring:
  datasource:
    url: jdbc:mysql://localhost:3308/test_database
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    #    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 12001